# 工具原理

## 原理
### 决策树规则

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import tree
from xgboost import XGBClassifier
from xgboost import plot_tree
import matplotlib.pyplot as plt
%matplotlib inline

# 演示

## 导入相关包

In [2]:
import os
import pandas as pd
import numpy as np
from shaphypetune.policy.rules_finder import *
import re

/home/ubuntu/miniforge3/envs/basefrm_latest/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/ubuntu/miniforge3/envs/basefrm_latest/lib/python3.11/site-packages/hyperopt/atpe.py:19: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

## 分类方法

### 读取数据集

In [2]:
##读取数据集
dataTrain = pd.read_csv(r'Train_samples.csv')
print('数据集结构：', dataTrain.shape)
print('变量维度：', len(dataTrain.columns))
dataTrain = dataTrain.rename(columns={'fpd4':'label'})
#选择可用的变量空间
feaSpace = [i for i in dataTrain.columns if i not in ['create_month', 'label', 'cust_no']]

数据集结构： (3141, 189)
变量维度： 189

### 工具演示

#### 决策树方法

In [6]:
result=atsr_rule_finder_clf(data=dataTrain, n_rounds=20, num_feature_min=2, num_feature_max=5, params=feaSpace[:20], label='label', depth=7, min_samples_leaf=100, random_state=None)

100%|██████████| 20/20 [00:00<00:00, 122.36it/s]

In [7]:
df_reports = atsr_report_clf(dataTrain, result, rule_col='rule_str', label='label', groups='create_month', id_col='cust_no')
df_reports.head()

             Processing (credit_general_credit_score<=556.5) & (credit_general_credit_score>526.5) & (bwjk_score>25.2450008392334) & (ali_rain_score<=75.32499694824219)              : 100%|██████████| 788/788 [00:25<00:00, 31.13it/s]

                                                       cnt                  \
create_month                                       2020-01 2020-02 2020-03
(ab_local_cnt>2.5) & (ab_local_cnt<=7.5) & (cre...    21.0    14.0    32.0
(ab_local_cnt<=7.5) & (credit_general_credit_sc...    46.0    30.0    67.0
(credit_general_credit_score<=407.5) & (credit_...    33.0    23.0    29.0
(ab_local_cnt<=68.5) & (ab_local_cnt>7.5) & (cr...    21.0    12.0    33.0
(credit_general_credit_score>366.0) & (credit_g...    57.0    41.0    62.0

                                                                    label  \
create_month                                       2020-04    All 2020-01
(ab_local_cnt>2.5) & (ab_local_cnt<=7.5) & (cre...    34.0  101.0     4.0
(ab_local_cnt<=7.5) & (credit_general_credit_sc...   161.0  304.0     5.0
(credit_general_credit_score<=407.5) & (credit_...    49.0  134.0     5.0
(ab_local_cnt<=68.5) & (ab_local_cnt>7.5) & (cr...    41.0  107.0     3.0
(credit_general_credit_score>366.0) & (credit_g...    89.0  249.0     7.0

                                                                            \
create_month                                       2020-02 2020-03 2020-04
(ab_local_cnt>2.5) & (ab_local_cnt<=7.5) & (cre...     2.0     6.0    10.0
(ab_local_cnt<=7.5) & (credit_general_credit_sc...     5.0     8.0    21.0
(credit_general_credit_score<=407.5) & (credit_...     3.0     2.0     7.0
(ab_local_cnt<=68.5) & (ab_local_cnt>7.5) & (cr...     1.0     3.0     6.0
(credit_general_credit_score>366.0) & (credit_g...     5.0     2.0    11.0

                                                         label_pct            \
create_month                                         All   2020-01   2020-02
(ab_local_cnt>2.5) & (ab_local_cnt<=7.5) & (cre...  22.0  0.190476  0.142857
(ab_local_cnt<=7.5) & (credit_general_credit_sc...  39.0  0.108696  0.166667
(credit_general_credit_score<=407.5) & (credit_...  17.0  0.151515  0.130435
(ab_local_cnt<=68.5) & (ab_local_cnt>7.5) & (cr...  13.0  0.142857  0.083333
(credit_general_credit_score>366.0) & (credit_g...  25.0  0.122807  0.121951

                                                                        \
create_month                                         2020-03   2020-04
(ab_local_cnt>2.5) & (ab_local_cnt<=7.5) & (cre...  0.187500  0.294118
(ab_local_cnt<=7.5) & (credit_general_credit_sc...  0.119403  0.130435
(credit_general_credit_score<=407.5) & (credit_...  0.068966  0.142857
(ab_local_cnt<=68.5) & (ab_local_cnt>7.5) & (cr...  0.090909  0.146341
(credit_general_credit_score>366.0) & (credit_g...  0.032258  0.123596

                                                                  lift  \
create_month                                             All   2020-01
(ab_local_cnt>2.5) & (ab_local_cnt<=7.5) & (cre...  0.217822  3.696429
(ab_local_cnt<=7.5) & (credit_general_credit_sc...  0.128289  2.109375
(credit_general_credit_score<=407.5) & (credit_...  0.126866  2.940341
(ab_local_cnt<=68.5) & (ab_local_cnt>7.5) & (cr...  0.121495  2.772321
(credit_general_credit_score>366.0) & (credit_g...  0.100402  2.383224

                                                                        \
create_month                                         2020-02   2020-03
(ab_local_cnt>2.5) & (ab_local_cnt<=7.5) & (cre...  2.582857  5.191406
(ab_local_cnt<=7.5) & (credit_general_credit_sc...  3.013333  3.305970
(credit_general_credit_score<=407.5) & (credit_...  2.358261  1.909483
(ab_local_cnt<=68.5) & (ab_local_cnt>7.5) & (cr...  1.506667  2.517045
(credit_general_credit_score>366.0) & (credit_g...  2.204878  0.893145


create_month                                         2020-04       All
(ab_local_cnt>2.5) & (ab_local_cnt<=7.5) & (cre...  4.896437  4.276114
(ab_local_cnt<=7.5) & (credit_general_credit_sc...  2.171464  2.518483
(credit_general_credit_score<=407.5) & (credit_...  2.378270  2.490532
(ab_local_cnt<=68.5) & (ab_local_cnt>7.5) & (cr...  2.436276  2.385105
(credit_general_credit_score>366.0) & (credit_g...  2.057604  1.971009

In [8]:
print(atsr_rule_finder_clf.__doc__)

自动生成规则，并获得所有规则对应的统计指标 - 分类

    Parameters
    ----------
    data :pd.DataFrame
        训练集
    n_rounds :int
        生成多少棵决策树
    num_feature_min:int
        规则包含的最小变量数
    num_feature_max:int
        规则包含的最大变量数
    params:list
        规则生成所使用的变量空间
    label:str
        指定目标变量
    depth:int
        决策树深度，与生成的规则复杂度有关
    min_samples_leaf:int
        叶节点最小样本数
    random_state:int
        伪随机数

    Returns
    -------
    data_class:pd.DataFrame
        生成规则、和对应的0 样本个数、以及正样本比例

In [9]:
print(atsr_report_clf.__doc__)

生成规则报告-分类

    Parameters
    ----------
    data :pd.DataFrame
        数据样本集
    rule_df :pd.DataFrame
        规则集
    rule_col ：str
        规则集变量，默认为'rule_str'
    label :str
        指定目标变量（0、1二分类）,默认为'fpd4'
    groups :str
        指定切片变量，默认为'create_month'
    id_col :str
        指定数据集唯一标识

    Returns
    -------
    data_report :pd.DataFrame
        规则报告

#### xgboost方法

In [4]:
result = atsr_rule_finder_clf_xgb(dataTrain, n_rounds=100, params=feaSpace, label='label', depth=7, min_samples_leaf=50, random_state=None)

In [5]:
df_reports = atsr_report_clf(dataTrain, result, rule_col='rule_str', label='label', groups='create_month', id_col='cust_no')
df_reports.head()

             Processing (cs_swg_bai_score>=62.0999985)              : 100%|██████████| 146/146 [00:04<00:00, 30.01it/s]

                                        cnt                                  \
create_month                        2020-01 2020-02 2020-03 2020-04     All
(ali_rain_score<75.1999969)           297.0   256.0   553.0   723.0  1829.0
(ali_rain_score>=75.1999969)          324.0   196.0   333.0   459.0  1312.0
(upa_debit_card_score<12.0)           270.0   161.0   374.0   701.0  1506.0
(upa_debit_card_score>=12.0)          351.0   291.0   512.0   481.0  1635.0
(credit_repayment_score_bj_2<522.0)   271.0   177.0   277.0   390.0  1115.0

                                      label                                 \
create_month                        2020-01 2020-02 2020-03 2020-04    All
(ali_rain_score<75.1999969)             5.0     8.0    13.0    28.0   54.0
(ali_rain_score>=75.1999969)           27.0    17.0    19.0    43.0  106.0
(upa_debit_card_score<12.0)            19.0    18.0    23.0    56.0  116.0
(upa_debit_card_score>=12.0)           13.0     7.0     9.0    15.0   44.0
(credit_repayment_score_bj_2<522.0)    20.0    15.0    16.0    40.0   91.0

                                    label_pct                                \
create_month                          2020-01   2020-02   2020-03   2020-04
(ali_rain_score<75.1999969)          0.016835  0.031250  0.023508  0.038728
(ali_rain_score>=75.1999969)         0.083333  0.086735  0.057057  0.093682
(upa_debit_card_score<12.0)          0.070370  0.111801  0.061497  0.079886
(upa_debit_card_score>=12.0)         0.037037  0.024055  0.017578  0.031185
(credit_repayment_score_bj_2<522.0)  0.073801  0.084746  0.057762  0.102564

                                                   lift                      \
create_month                              All   2020-01   2020-02   2020-03
(ali_rain_score<75.1999969)          0.029524  0.326705  0.565000  0.650882
(ali_rain_score>=75.1999969)         0.080793  1.617188  1.568163  1.579767
(upa_debit_card_score<12.0)          0.077025  1.365625  2.021366  1.702707
(upa_debit_card_score>=12.0)         0.026911  0.718750  0.434914  0.486694
(credit_repayment_score_bj_2<522.0)  0.081614  1.432196  1.532203  1.599278


create_month                          2020-04       All
(ali_rain_score<75.1999969)          0.644731  0.579600
(ali_rain_score>=75.1999969)         1.559606  1.586061
(upa_debit_card_score<12.0)          1.329931  1.512102
(upa_debit_card_score>=12.0)         0.519165  0.528303
(credit_repayment_score_bj_2<522.0)  1.707476  1.602192

In [6]:
print(atsr_rule_finder_clf_xgb.__doc__)

用于生成xgboost模型规则 - 分类

    Parameters
    ----------
    data :pd.DataFrame
        数据样本集
    n_rounds :
        模型迭代次数
    params:list
        规则生成所使用的变量空间
    label :str
        指定目标变量
    depth:int
        决策树深度，与生成的规则复杂度有关
    min_samples_leaf :int
        叶节点最小样本数
    random_state:int
        伪随机数

    Returns
    -------
    rule_df:pd.DataFrame
        生成的规则表

## 回归方法

### 读取数据集

In [7]:
##读取数据集
dataTrain  = pd.read_csv('OOT_sample_reg.csv')
print('数据集结构：', dataTrain.shape)
print('变量维度：', len(dataTrain.columns))
dataTrain = dataTrain.rename(columns={'profit' : 'cost'})
feaSpace = [i for i in dataTrain.columns if i not in ['create_month', 'profit', 'cust_no']]

数据集结构： (54395, 158)
变量维度： 158

### 工具演示

#### 决策树方法

In [8]:
result = atsr_rule_finder_reg(dataTrain, n_rounds=10, num_feature_min=2, num_feature_max=5, params=feaSpace, 
                              label='cost', depth=7, min_samples_leaf=1000)

100%|██████████| 10/10 [00:00<00:00, 16.15it/s]

In [9]:
df_reports = atsr_report_reg(dataTrain, result, rule_col='rule_str', label='cost', groups='create_month', id_col='cust_no')
df_reports.head()

             Processing (cost>3726.263427734375)              : 100%|██████████| 532/532 [00:21<00:00, 24.56it/s]

                                                       cnt          \
create_month                                       2019-08     All
(tag1_video_download_sum<=3731125504.0) & (tag2...  1974.0  1974.0
(tag2_music_pop_mean>9751.75) & (tag2_music_pop...  3848.0  3848.0
(tag1_video_download_sum<=4588163072.0) & (tag1...  1001.0  1001.0
(tag1_video_download_sum<=5040324096.0) & (tag1...  1677.0  1677.0
(tag1_video_download_sum>3731125504.0) & (tag2_...  1874.0  1874.0

                                                          cost              \
create_month                                           2019-08         All
(tag1_video_download_sum<=3731125504.0) & (tag2... -389.510486 -389.510486
(tag2_music_pop_mean>9751.75) & (tag2_music_pop... -323.793331 -323.793331
(tag1_video_download_sum<=4588163072.0) & (tag1... -291.633440 -291.633440
(tag1_video_download_sum<=5040324096.0) & (tag1... -257.365314 -257.365314
(tag1_video_download_sum>3731125504.0) & (tag2_... -254.569391 -254.569391

                                                          lift
create_month                                           2019-08         All
(tag1_video_download_sum<=3731125504.0) & (tag2... -352.581696 -352.581696
(tag2_music_pop_mean>9751.75) & (tag2_music_pop... -286.864541 -286.864541
(tag1_video_download_sum<=4588163072.0) & (tag1... -254.704650 -254.704650
(tag1_video_download_sum<=5040324096.0) & (tag1... -220.436523 -220.436523
(tag1_video_download_sum>3731125504.0) & (tag2_... -217.640601 -217.640601

In [12]:
print(atsr_rule_finder_reg.__doc__)

自动生成规则，并获得所有规则对应的统计指标 - 回归

    Parameters
    ----------
    data：pd.DataFrame)
        训练集
    n_rounds:int
        生成多少棵决策树
    num_feature_min :int
        规则包含的最小变量数
    num_feature_max:int
        规则包含的最大变量数
    params:list
        规则生成所使用的变量空间
    label :str
        指定目标变量
    depth:int
        决策树深度，与生成的规则复杂度有关
    min_samples_leaf :int
        叶节点最小样本数
    random_state:int
        伪随机数

    Returns
    -------
    data_class:pd.DataFrame
        生成规则、和对应的分裂节点及叶节点的样本个数、以及目标变量均值

In [13]:
print(atsr_report_reg.__doc__)

生成规则报告-回归

    Parameters
    ----------
    data :pd.DataFrame
        数据样本集
    rule_df :pd.DataFrame
        规则集
    rule_col：str
        规则集变量，默认为'rule_str'
    label :str
        指定目标变量（连续变量）,默认为'profit'
    groups：str
        指定切片变量，默认为'create_month'
    id_col:str
        指定数据集唯一标识

    Returns
    -------
    data_report :pd.DataFrame
        规则报告

#### xgboost方法

In [14]:
result = atsr_rule_finder_reg_xgb(dataTrain, n_rounds=100, params=feaSpace, label='cost', depth=7, min_samples_leaf=50, random_state=None)

In [15]:
df_reports = atsr_report_reg(dataTrain, result, rule_col='rule_str', label='cost', groups='create_month', id_col='cust_no')
df_reports.head()

             Processing (cost>=4434.63867) & (mob_contain_4_ratio>=0.566037714)              : 100%|██████████| 2665/2665 [01:31<00:00, 29.00it/s]

                                             cnt                 cost  \
create_month                             2019-08    All       2019-08
(cost<-18452.7363)                         214.0  214.0 -21435.968606
(cost<-15541.1895) & (cost>=-18452.7363)   211.0  211.0 -16943.829203
(cost<-13715.5088) & (cost>=-15541.1895)   213.0  213.0 -14646.112170
(cost<-11905.0186) & (cost>=-13715.5088)   214.0  214.0 -12789.805884
(cost<-10582.1016) & (cost>=-11905.0186)   212.0  212.0 -11270.525966

                                                                lift  \
create_month                                       All       2019-08
(cost<-18452.7363)                       -21435.968606 -21399.039816
(cost<-15541.1895) & (cost>=-18452.7363) -16943.829203 -16906.900412
(cost<-13715.5088) & (cost>=-15541.1895) -14646.112170 -14609.183379
(cost<-11905.0186) & (cost>=-13715.5088) -12789.805884 -12752.877094
(cost<-10582.1016) & (cost>=-11905.0186) -11270.525966 -11233.597175


create_month                                       All
(cost<-18452.7363)                       -21399.039816
(cost<-15541.1895) & (cost>=-18452.7363) -16906.900412
(cost<-13715.5088) & (cost>=-15541.1895) -14609.183379
(cost<-11905.0186) & (cost>=-13715.5088) -12752.877094
(cost<-10582.1016) & (cost>=-11905.0186) -11233.597175

In [20]:
print(atsr_rule_finder_reg_xgb.__doc__)

用于生成xgboost模型规则 - 回归

    Parameters
    ----------
    data :pd.DataFrame
        数据样本集
    n_rounds :
        模型迭代次数
    params:list
        规则生成所使用的变量空间
    label :str
        指定目标变量
    depth:int
        决策树深度，与生成的规则复杂度有关
    min_samples_leaf :int
        叶节点最小样本数
    random_state:int
        伪随机数

    Returns
    -------
    rule_df:pd.DataFrame
        生成的规则表